# Generated by Django 4.2.3 on 2023-08-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgsrc1', models.ImageField(upload_to='ptt')),
                ('name1', models.CharField(max_length=250)),
                ('des1', models.TextField()),
            ],
        ),
    ]
